/**
 * This package contains interfaces describing objects retrieved from the ESI
 * API.
 *
 * All implementations generated by the client are thread-safe and immutable.
 */
package gbsio.esiclient.api.domain.response;