package gbsio.esiclient.client.request.killmails;

import com.fasterxml.jackson.core.type.TypeReference;
import com.google.common.base.Preconditions;
import com.google.common.collect.ImmutableList;
import gbsio.esiclient.api.domain.response.killmails.KillmailIDHash;
import gbsio.esiclient.api.request.specific.GetListRequest;

import java.util.Optional;

/**
 * Retrieves the IDs/hashes of killmails generated by a character within the
 * last 90 days.
 */
final public class CharacterKillmailsRequest implements GetListRequest<KillmailIDHash, ImmutableList<KillmailIDHash>> {
    private final int characterID;
    private final String accessToken;

    /**
     * @param characterID the ID of the character to query
     * @param accessToken an OAuth2 access token for said character
     */
    public CharacterKillmailsRequest(final int characterID, final String accessToken) {
        this.characterID = characterID;
        this.accessToken = Preconditions.checkNotNull(accessToken);
    }

    @Override
    public String getURL() {
        return String.format("/v1/characters/%d/killmails/recent/", characterID);
    }

    @Override
    public TypeReference<ImmutableList<KillmailIDHash>> getExpectedType() {
        return new TypeReference<ImmutableList<KillmailIDHash>>() {
        };
    }

    @Override
    public Optional<String> getAccessToken() {
        return Optional.of(accessToken);
    }
}
