package gbsio.esiclient.api.domain.response.character;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import gbsio.esiclient.api.domain.response.common.SenderType;
import gbsio.esiclient.internal.domain.response.character.NotificationImpl;

import java.time.ZonedDateTime;
import java.util.Optional;

/**
 * Represents a notification generated by the Eve servers.
 */
@JsonDeserialize(as = NotificationImpl.class)
public interface Notification {
    /**
     * Get the unique ID for this notification.
     *
     * @return the notification ID
     */
    long getNotificationID();

    /**
     * Get the sender's ID.
     *
     * This information is useless without {@link #getSenderType()}.
     *
     * @return the sender's ID
     */
    int getSenderID();

    /**
     * Get the type of sender.
     *
     * @return the type of sender
     */
    SenderType getSenderType();

    /**
     * Get the notification body.
     *
     * @return the notification body
     */
    String getText();

    /**
     * Get the timestamp for this notification.
     *
     * @return the notification timestamp
     */
    ZonedDateTime getTimestamp();

    /**
     * Get the type of notification.
     *
     * @return the notification type
     */
    String getType();

    /**
     * Get whether or not the notification has been read.
     *
     * @return true if the notification was read
     */
    Optional<Boolean> isRead();
}
