/**
 * This package contains interfaces describing wrappers around responses from
 * the ESI API.
 * <p>
 * All objects generated by the client that implement these interfaces are
 * guaranteed to be immutable.
 */
package gbsio.esiclient.api.response;